version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      SECRET: somehashvalue
    depends_on:
      - mongodb
    networks:
      - my-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network

networks:
  my-network:
